### PR TITLE
Ship `leap-seconds.list`

### LINKED ISSUE #28: Ship `leap-seconds.list`
our tzdata [contains](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Fnoarch%2Ftzdata-2024a-h0c530f3_0.conda) `leapseconds`, but not `leap-seconds.list`, which can apparently be found in some forms of the tzdata distribution (c.f. #26). The issue is that libcxx currently only [supports](https://github.com/llvm/llvm-project/blob/llvmorg-19.1.0-rc1/libcxx/docs/DesignDocs/TimeZone.rst#leap-seconds) parsing `leap-seconds.list`, but not `leapseconds`, so we need to add this to our `tzdata` to properly [support](https://github.com/conda-forge/libcxx-feedstock/pull/178) C++20's `<chrono>`.

@conda-forge/tzdata

### PR DESCRIPTION
**Pull request by h-vetinari**
Closes #28

### CODE REVIEW

**Comment by h-vetinari** [comment]
OK, after suffering much shell scripting differences between osx & linux, I've got a pretty minimal fix now. PTAL @conda-forge/tzdata :)

**Comment by h-vetinari** [comment]
@conda-forge/tzdata, could someone PTAL? :)

**Comment by h-vetinari** [comment]
As a side benefit, this will also help with https://github.com/conda-forge/ctng-compilers-feedstock/pull/148 :)

**Review by hmaarrfk — APPROVED** [review]

**Comment by h-vetinari** [comment]
Thanks @hmaarrfk!

**Pull request merged**
